# Current node lts version
FROM node:14.17.0-alpine as build-stage

WORKDIR /app/frontend/

COPY . /app/frontend/

RUN npm install

ARG REACT_APP_NAME

ENV REACT_APP_NAME=$REACT_APP_NAME

ARG REACT_APP_FUCK

ENV REACT_APP_FUCK=$REACT_APP_FUCK

RUN npm run build

FROM nginx:stable-alpine as run-stage

RUN rm /etc/nginx/conf.d/default.conf

COPY --from=build-stage /app/frontend/build /usr/share/nginx/html

COPY nginx/nginx.conf /etc/nginx/conf.d

CMD ["nginx", "-g", "daemon off;"]