version: "3"
services:
    reverse-proxy:
        image: nginx:stable-alpine
        container_name: reverse_proxy
        depends_on:
            - frontend
            - backend
        volumes:
            - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
            #- 443:443
        networks:
            - front
            - back
        # volumes:
        #     - <path/to/your/config>:/etc/nginx
        #     - <path/to/your/certs>:/etc/ssl/private 

    frontend:
        image: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile.prod
            args:
                - REACT_APP_NAME=PROD
        environment: 
            - REACT_APP_BACKEND_API_HOST=${REACT_APP_BACKEND_API_HOST}
        depends_on:
            - backend
        ports:
            - 3000:80
        networks:
            - front

    backend:
        image: backend
        build:
            context: ./backend
            dockerfile: Dockerfile.prod
        networks:
            - front
            - back
        environment: 
            - NODE_ENV=production
        depends_on: 
            - db
        ports:
            - 8000:8000

    db: # this is the server name field of phpmyadmin
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: nex
            MYSQL_DATABASE: fresher
        volumes:
            - type: volume
              source: mysql-volume
              target: /var/lib/mysql
        networks:
            - back

    phpmyadmin:
        depends_on: 
            - db
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db
        networks:
            - back

volumes:
    mysql-volume:
        name: "mysql-volume"
networks:
    front:
    back: