version: "3"
services:
    db: # this is the server name field of phpmyadmin
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: nex
            MYSQL_DATABASE: fresher
    phpmyadmin:
        depends_on: 
            - db
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db
