version: "3"
services:
    frontend:
        image: frontend:dev
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - ./frontend/src/:/app/frontend/src
        environment: 
            - REACT_APP_NAME=kuyraiyedmae-dev